server:
  address: ":8443"
  readTimeout: 10s
  writeTimeout: 10s 

logger:
  level: debug
  addCaller: true
  outputPaths:
    - stdout

database:
  DSN: "/tmp/models_test.db"
  dialect: "sqlite3"

nodes:
  - "http://127.0.0.1:9000/file"
  - "http://127.0.0.1:9001/file"
  - "http://127.0.0.1:9002/file"
  - "http://127.0.0.1:9003/file"
  - "http://127.0.0.1:9004/file"
  - "http://127.0.0.1:9005/file"
  - "http://127.0.0.1:9006/file"
  - "http://127.0.0.1:9007/file"
  - "http://127.0.0.1:9008/file"
  - "http://127.0.0.1:9009/file"
